FROM python:3.9-alpine

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY app.py .

# Важно: Flask должен запускаться в режиме разработки или через production server
CMD ["python", "app.py"]
